Aegis Talisman: 0
Anemone(Back): 1
Anemone(Horn): 2
Ant: 3
Antenna: 4
Arco: 5
Axie Kiss: 6
Baby: 7
Babylonia: 8
Balloon: 9
Bamboo Shoot: 10
Beech: 11
Beetle Spike: 12
Beetroot: 13
Belieber: 14
Bidens: 15
Blackmail: 16
Blossom: 17
Blue Moon: 18
Bone Sail: 19
Bookworm: 20
Buba Brush: 21
Bubblemaker: 22
Bumpy: 23
Burn: 24
Buzz Buzz: 25
Cactus: 26
Carrot: 27
Caterpillars: 28
Catfish: 29
Cattail: 30
Cerastes: 31
Chubby: 32
Clamshell: 33
Clear: 34
Cloud: 35
Clover: 36
Confident: 37
Confused: 38
Confusion: 39
Cottontail: 40
Croc: 41
Cub: 42
Cuckoo: 43
Cucumber Slice: 44
Cupid: 45
Curly: 46
Curved Spine: 47
Cute Bunny: 48
Daze: 49
DeadAttack3: 50
DeadSecret3: 51
DeadSkill3: 52
Doubletalk: 53
Dual Blade: 54
Ear Breathing: 55
Early Bird: 56
Earwing: 57
Eggshell: 58
Energy Coin: 59
Feather Fan: 60
Feather Spear: 61
Fish Snack: 62
Forest Breath: 63
Forest Hero: 64
Forest Wrath: 65
Foxy(Ears): 66
Foxy(Mouth): 67
Friezard: 68
Furball: 69
Garish Worm: 70
Gecko: 71
Gerbil: 72
Gero: 73
Gila: 74
Gill: 75
Goda: 76
Goldfish: 77
Goo: 78
Granma's Fan: 79
Grass Snake: 80
Gravel Ant: 81
Green Thorns: 82
Hare: 83
Hatsune: 84
Herbivore: 85
Hermit: 86
Hero: 87
Hidden Ears: 88
Hollow: 89
Hot Butt: 90
Hungry Bird: 91
Iguana: 92
Imp: 93
Incisor: 94
Indian Star: 95
Inkling: 96
Innocent Lamb: 97
Jaguar: 98
Jellytacle: 99
Jinx: 100
Kestrel: 101
Kingfisher: 102
Koi: 103
Kotaro(Eyes): 104
Kotaro(Mouth): 105
Lagging: 106
Lam: 107
Larva: 108
Leaf Bug(Ears): 109
Leaf Bug(Horn): 110
Leafy: 111
Little Branch: 112
Little Crab: 113
Little Owl(Ears): 114
Little Owl(Eyes): 115
Little Owl(Mouth): 116
Little Peas: 117
Lotus: 118
Lucas: 119
Lumber Shield: 120
Magic Sack: 121
Mandarine: 122
Mavis: 123
Merry: 124
Mint: 125
Mosquito: 126
Navaga: 127
Neo: 128
Nerdy: 129
Nimo(Ears): 130
Nimo(Tail): 131
Nut Cracker(Ears): 132
Nut Cracker(Mouth): 133
Nut Cracker(Tail): 134
Nyan: 135
Oranda: 136
Pacu: 137
Papi: 138
Parasite: 139
Peace Maker(Ears): 140
Peace Maker(Mouth): 141
Perch: 142
Persimmon: 143
Pigeon Post: 144
Pincer: 145
Pink Cheek: 146
Piranha: 147
Pliers: 148
Pocky: 149
Pogona: 150
Post Fight: 151
Potato Leaf: 152
Puff(Mouth): 153
Puff(Tail): 154
Pumpkin: 155
Pupae: 156
Puppy(Ears): 157
Puppy(Eyes): 158
Pure Water: 159
Ranchu: 160
Raven: 161
Razor Bite: 162
Red Ear: 163
Rice: 164
Risky Beast: 165
Risky Bird: 166
Risky Fish: 167
Risky Trunk: 168
Robin: 169
Ronin: 170
Rosa: 171
Rose Bud: 172
Rusty Helm: 173
Sakura: 174
Sandal: 175
Scaly Spear: 176
Scaly Spoon: 177
Scar: 178
Scarab: 179
Scorch: 180
Seaslug: 181
Serious: 182
Shiba: 183
Shiitake: 184
Shoal Star: 185
Shrimp: 186
Shuriken: 187
Sidebarb: 188
Silence Whisper: 189
Sleepless: 190
Small Frill: 191
Snail Shell: 192
Snake Jar: 193
Sparky: 194
Spiky Wing: 195
Sponge: 196
Sprout: 197
Square Teeth: 198
Strawberry: 199
Strawberry Shortcake: 200
Succulent: 201
Swallow: 202
Swirl: 203
Tadpole: 204
Tassels: 205
Teal Shell: 206
Telescope: 207
The Fallen's Axe: 208
The Fallen's Gloves: 209
The Fallen's Helmet: 210
The Fallen's Hidden Bomb: 211
The Fallen's Hidden Knife: 212
The Fallen's Longsword: 213
The Fallen's Shield: 214
The Fallen's Shortsword: 215
The Fallen's Soul: 216
The Fallen's Tetsubishi: 217
The Last One: 218
Thorny Caterpillar: 219
Timber: 220
Tiny Dino(Tail): 221
Tiny Dino(Back): 222
Tiny Fan: 223
Tiny Turtle: 224
Toothless Bite: 225
Topaz: 226
Tri Feather: 227
Tri Spikes: 228
Tricky: 229
Trump: 230
Turnip: 231
Twin Tail: 232
Unko: 233
Void: 234
Wall Gecko: 235
Watering Can: 236
Watermelon: 237
Wing Horn: 238
Yam: 239
Zeal: 240
Zen: 241
Zigzag: 242
