# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rl_grpc/service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15rl_grpc/service.proto\x12\x07rl_grpc\"\x1c\n\x0b\x43\x61llRequest\x12\r\n\x05input\x18\x01 \x01(\t\"$\n\x0c\x43\x61llResponse\x12\x14\n\x0coutput_specs\x18\x01 \x01(\t2E\n\x0cModelService\x12\x35\n\x04\x43\x61ll\x12\x14.rl_grpc.CallRequest\x1a\x15.rl_grpc.CallResponse\"\x00\x62\x06proto3')



_CALLREQUEST = DESCRIPTOR.message_types_by_name['CallRequest']
_CALLRESPONSE = DESCRIPTOR.message_types_by_name['CallResponse']
CallRequest = _reflection.GeneratedProtocolMessageType('CallRequest', (_message.Message,), {
  'DESCRIPTOR' : _CALLREQUEST,
  '__module__' : 'rl_grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:rl_grpc.CallRequest)
  })
_sym_db.RegisterMessage(CallRequest)

CallResponse = _reflection.GeneratedProtocolMessageType('CallResponse', (_message.Message,), {
  'DESCRIPTOR' : _CALLRESPONSE,
  '__module__' : 'rl_grpc.service_pb2'
  # @@protoc_insertion_point(class_scope:rl_grpc.CallResponse)
  })
_sym_db.RegisterMessage(CallResponse)

_MODELSERVICE = DESCRIPTOR.services_by_name['ModelService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALLREQUEST._serialized_start=34
  _CALLREQUEST._serialized_end=62
  _CALLRESPONSE._serialized_start=64
  _CALLRESPONSE._serialized_end=100
  _MODELSERVICE._serialized_start=102
  _MODELSERVICE._serialized_end=171
# @@protoc_insertion_point(module_scope)
