algo_args:
  learning_rate: 0.0001
  alpha: 0.99
  momentum: 0
  epsilon: 0.00001 #1e-5
  max_grad_norm: 40
  batch_size: 32
  buffer_size: 100
  train_device: 'cpu' # cpu or 0, 1, 2, ...
  infer_device: 'cpu'
  close_log: True
  port: 6789
